//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsService.FastSendSoap")]
    public interface FastSendSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSendCode", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsService.AutoSendCodeResponse> AutoSendCodeAsync(SmsService.AutoSendCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageWithCode", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsService.SendMessageWithCodeResponse> SendMessageWithCodeAsync(SmsService.SendMessageWithCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckSendCode", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsService.CheckSendCodeResponse> CheckSendCodeAsync(SmsService.CheckSendCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoSendCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoSendCode", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.AutoSendCodeRequestBody Body;
        
        public AutoSendCodeRequest()
        {
        }
        
        public AutoSendCodeRequest(SmsService.AutoSendCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoSendCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReciptionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Footer;
        
        public AutoSendCodeRequestBody()
        {
        }
        
        public AutoSendCodeRequestBody(string Username, string Password, string ReciptionNumber, string Footer)
        {
            this.Username = Username;
            this.Password = Password;
            this.ReciptionNumber = ReciptionNumber;
            this.Footer = Footer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoSendCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoSendCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.AutoSendCodeResponseBody Body;
        
        public AutoSendCodeResponse()
        {
        }
        
        public AutoSendCodeResponse(SmsService.AutoSendCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoSendCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long AutoSendCodeResult;
        
        public AutoSendCodeResponseBody()
        {
        }
        
        public AutoSendCodeResponseBody(long AutoSendCodeResult)
        {
            this.AutoSendCodeResult = AutoSendCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageWithCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageWithCode", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.SendMessageWithCodeRequestBody Body;
        
        public SendMessageWithCodeRequest()
        {
        }
        
        public SendMessageWithCodeRequest(SmsService.SendMessageWithCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageWithCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReciptionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Code;
        
        public SendMessageWithCodeRequestBody()
        {
        }
        
        public SendMessageWithCodeRequestBody(string Username, string Password, string ReciptionNumber, string Code)
        {
            this.Username = Username;
            this.Password = Password;
            this.ReciptionNumber = ReciptionNumber;
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageWithCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageWithCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.SendMessageWithCodeResponseBody Body;
        
        public SendMessageWithCodeResponse()
        {
        }
        
        public SendMessageWithCodeResponse(SmsService.SendMessageWithCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageWithCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long SendMessageWithCodeResult;
        
        public SendMessageWithCodeResponseBody()
        {
        }
        
        public SendMessageWithCodeResponseBody(long SendMessageWithCodeResult)
        {
            this.SendMessageWithCodeResult = SendMessageWithCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSendCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckSendCode", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.CheckSendCodeRequestBody Body;
        
        public CheckSendCodeRequest()
        {
        }
        
        public CheckSendCodeRequest(SmsService.CheckSendCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckSendCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReciptionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Code;
        
        public CheckSendCodeRequestBody()
        {
        }
        
        public CheckSendCodeRequestBody(string Username, string Password, string ReciptionNumber, string Code)
        {
            this.Username = Username;
            this.Password = Password;
            this.ReciptionNumber = ReciptionNumber;
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSendCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckSendCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.CheckSendCodeResponseBody Body;
        
        public CheckSendCodeResponse()
        {
        }
        
        public CheckSendCodeResponse(SmsService.CheckSendCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckSendCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckSendCodeResult;
        
        public CheckSendCodeResponseBody()
        {
        }
        
        public CheckSendCodeResponseBody(bool CheckSendCodeResult)
        {
            this.CheckSendCodeResult = CheckSendCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface FastSendSoapChannel : SmsService.FastSendSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class FastSendSoapClient : System.ServiceModel.ClientBase<SmsService.FastSendSoap>, SmsService.FastSendSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FastSendSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(FastSendSoapClient.GetBindingForEndpoint(endpointConfiguration), FastSendSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FastSendSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FastSendSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FastSendSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FastSendSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FastSendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsService.AutoSendCodeResponse> SmsService.FastSendSoap.AutoSendCodeAsync(SmsService.AutoSendCodeRequest request)
        {
            return base.Channel.AutoSendCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsService.AutoSendCodeResponse> AutoSendCodeAsync(string Username, string Password, string ReciptionNumber, string Footer)
        {
            SmsService.AutoSendCodeRequest inValue = new SmsService.AutoSendCodeRequest();
            inValue.Body = new SmsService.AutoSendCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Footer = Footer;
            return ((SmsService.FastSendSoap)(this)).AutoSendCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsService.SendMessageWithCodeResponse> SmsService.FastSendSoap.SendMessageWithCodeAsync(SmsService.SendMessageWithCodeRequest request)
        {
            return base.Channel.SendMessageWithCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsService.SendMessageWithCodeResponse> SendMessageWithCodeAsync(string Username, string Password, string ReciptionNumber, string Code)
        {
            SmsService.SendMessageWithCodeRequest inValue = new SmsService.SendMessageWithCodeRequest();
            inValue.Body = new SmsService.SendMessageWithCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Code = Code;
            return ((SmsService.FastSendSoap)(this)).SendMessageWithCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsService.CheckSendCodeResponse> SmsService.FastSendSoap.CheckSendCodeAsync(SmsService.CheckSendCodeRequest request)
        {
            return base.Channel.CheckSendCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsService.CheckSendCodeResponse> CheckSendCodeAsync(string Username, string Password, string ReciptionNumber, string Code)
        {
            SmsService.CheckSendCodeRequest inValue = new SmsService.CheckSendCodeRequest();
            inValue.Body = new SmsService.CheckSendCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Code = Code;
            return ((SmsService.FastSendSoap)(this)).CheckSendCodeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FastSendSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FastSendSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FastSendSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://raygansms.com/FastSend.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.FastSendSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://raygansms.com/FastSend.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            FastSendSoap,
            
            FastSendSoap12,
        }
    }
}
